### PR TITLE
Added support for x509 certs for spinnaker

### PR DESCRIPTION
**Pull request by shazy792**

### CODE REVIEW

**Comment by xordspar0** [comment]
Currently ChaosMonkey only supports pkcs12 certificates. At Target, we use x509 certificates, so it's better for us to support that type. Our changes add support for x509 certificates in addition to the pkcs12 certificates already supported.

**Comment by lorin** [comment]
Apologies it's taking so long to review this PR, please note that I haven't forgotten about it.

**Comment by lorin** [comment]
@shazy792 Finally merged this, thanks for the contribution. When you get a chance, can you update the documentation so that users know that x509 certs are now supported?

The docs are in the docs directory of the repo. It's probably sufficient to update the [Configuration-file-format.md](https://github.com/Netflix/chaosmonkey/blob/master/docs/Configuration-file-format.md) file. Generated docs are served as http://netflix.github.io/chaosmonkey, but I suspect you already know that.

**Comment by edwinavalos** [comment]
@lorin the two team members thats worked on this rotated off our team (or went back to school *glares* at Shaz), I can own getting the documentation update.

**Pull request merged**
