### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by KhurramJalil**
Fix: #90

### CODE REVIEW

**Comment by KhurramJalil** [comment]
@lorin, @prytoegrian, @anotherchrisberry, @d6o, @aplsek, @sbasgall, @shawnps, @haleyw, @adamdmharvey, @oremj, @robzienert Can anyone please review this PR which fixes #90 ?

**Review by d6o — APPROVED** [review]
LGTM

**Comment by KhurramJalil** [comment]
Thanks for reviewing / approving this @d6o.

I see the message "Only those with write access to this repository can merge pull request" so @lorin, @prytoegrian, @anotherchrisberry, @d6o, @aplsek, @sbasgall, @shawnps, @haleyw, @adamdmharvey, @oremj, @robzienert please do the needful to merge this PR whoever has the write access.

**Comment by KhurramJalil** [comment]
Thanks @robzienert for merging this.

**Comment by robzienert** [comment]
You got it. Thanks for opening it!

**Pull request merged**
